//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasoEstudio2.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CasoEstudioKNEntities : DbContext
    {
        public CasoEstudioKNEntities()
            : base("name=CasoEstudioKNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasasSistema> CasasSistemas { get; set; }
    
        public virtual int SP_AlquilarCasa(Nullable<long> idCasa, string usuarioAlquiler)
        {
            var idCasaParameter = idCasa.HasValue ?
                new ObjectParameter("IdCasa", idCasa) :
                new ObjectParameter("IdCasa", typeof(long));
    
            var usuarioAlquilerParameter = usuarioAlquiler != null ?
                new ObjectParameter("UsuarioAlquiler", usuarioAlquiler) :
                new ObjectParameter("UsuarioAlquiler", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AlquilarCasa", idCasaParameter, usuarioAlquilerParameter);
        }
    
        public virtual ObjectResult<SP_CasasDisponibles_Result> SP_CasasDisponibles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CasasDisponibles_Result>("SP_CasasDisponibles");
        }
    
        public virtual ObjectResult<SP_ConsultarCasas_Result> SP_ConsultarCasas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarCasas_Result>("SP_ConsultarCasas");
        }
    
        public virtual ObjectResult<SP_ObtenerCasaPorId_Result> SP_ObtenerCasaPorId(Nullable<long> idCasa)
        {
            var idCasaParameter = idCasa.HasValue ?
                new ObjectParameter("IdCasa", idCasa) :
                new ObjectParameter("IdCasa", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerCasaPorId_Result>("SP_ObtenerCasaPorId", idCasaParameter);
        }
    }
}
